# -*- coding: utf-8 -*-
"""AI_Exp01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19R5F6p7ZzmTtTsoMDXsQ_ZouaQ00aO_-
"""

file1=open("/content/myfile.txt","r")
text=file1.read()
print(text)

file2=open("/content/myfile.txt","r")
text=file2.readlines()
print(text)

file_path="/content/myfile.txt"
def count_lines(file_path):
  with open(file_path,"r") as file:
    lines=file.readlines()
    return len(lines)

count=count_lines(file_path)
print(f"The file contains {count} lines.")

def count_fields(file_path):
  with open(file_path,"r",errors='ignore') as file:
    first_line=file.readline().strip()
    fields=first_line.split()
    return len(fields)

file_path="/content/myfile.txt"
field_count=count_fields(file_path)
print(f"The number of fields in the first line is:{field_count}")

import pandas as pd
df = pd.read_csv("/content/data.tsv", delimiter='\t', encoding='latin-1')
df.head()

rows=df.shape[0]
cols=df.shape[1]
print(" Number of Rows:",rows)
print("Number ofColumns:",cols)

file_path="/content/data.tsv"
def count_lines(file_path):
  with open(file_path,"r",errors="ignore") as file:
    lines=file.readlines()
    return len(lines)

line_count=count_lines(file_path)
print(f"Number of lines in the file: {line_count}")

def count_fields(file_path):
  with open(file_path,"r")as file:
    first_line=file.readline().strip()
    fields=first_line.split()
    return len(fields)

field_count=count_fields(file_path)
print(f"Number of fields are: {field_count}")